version: "3.6"

volumes:
  shared-workspace:
    name: "distributed-file-system"
    driver: local

services:
  jupyterlab:
    image: spark-cluster-jupyter:latest
    container_name: jupyterlab
    ports:
      - 8888:8888    # JupyterLab
      - 4040:4040    # Spark UI（第一个应用可能使用 4040 端口）
    volumes:
      - shared-workspace:/opt/workspace

  spark-master:
    image: spark-cluster-spark-master:latest
    container_name: spark-master
    ports:
      - 8080:8080    # Spark Master UI
      - 7077:7077    # Spark Master RPC
      - 18080:18080  # History Server UI
    volumes:
      - shared-workspace:/opt/workspace

  spark-worker-1:
    image: spark-cluster-spark-worker:latest
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081    # Spark Worker UI
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: spark-cluster-spark-worker:latest
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081    # 第二个 Worker: 宿主机用 8082 来映射容器 8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
