# Dockerfile.spark-worker
ARG spark_version
FROM spark-cluster-base
LABEL maintainer="zyl"

# -- Layer: Image Metadata
ARG build_date
LABEL org.label-schema.build-date=${build_date}
LABEL org.label-schema.description="Spark worker image"
LABEL org.label-schema.schema-version="1.0"

# -- Runtime
# 8081 用于 Spark Worker 的 Web UI
EXPOSE 8081

CMD bin/spark-class org.apache.spark.deploy.worker.Worker spark://${SPARK_MASTER_HOST}:${SPARK_MASTER_PORT}
